# Generated by Django 5.2.17 on 2026-09-12 12:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('business_plan', 'Business Plan'), ('scientific_paper', 'Scientific Paper / Karya Ilmiah'), ('interview_report', 'Interview Report')], default='scientific_paper', max_length=30)),
                ('year', models.PositiveIntegerField()),
                ('link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
