# Generated by Django 5.2.17 on 2026-09-13 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_project_pdf_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='pdf_file',
        ),
        migrations.AddField(
            model_name='project',
            name='link_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
