# Generated by Django 5.2.17 on 2026-09-20 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_project_pdf_file_project_link_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='ended_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='started_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
